### ISSUE TITLE
MutationBuffTimer not working

### ISSUE THREAD

**Issue by WarBird25** [Anthony-George449/ASA-Imprint-Kibble#1]
Thank you for the mod!

We have one problem on the Server. I set MutationBuffTimer=900.0 and the buff is showing the 900 seconds. But when the timer runs out the buff is still active and reseting mating cooldown. Ist this a bug?

private server with some other mods (no dino mods or anything related to dinos)

**Comment by WarBird25** [comment]
The buff is applied until the next server restart and is not shown in "Show Buffs".

**Comment by Anthony-George449** [comment]
Thanks for letting me know about this bug. The latest update should have fixed this.
